"""Generate notebooks/submit/ (a Kaggle notebook that writes /kaggle/working/submission.zip) from submission/.

Submissions to this competition are made from a notebook's output, so the notebook just embeds every
file of submission/ and zips them. Text files only; LoRA adapters must come from an attached Kaggle
dataset instead (see ADAPTER_DATASET below) because they are too big to inline.

Usage:
  python scripts/make_submit_notebook.py --version v1 --note "coder+analyzer, default budgets"
  kaggle kernels push -p notebooks/submit
  (wait for the run to finish, then submit its output with `kaggle competitions submit`)
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SUB = ROOT / "submission"
OUT = ROOT / "notebooks" / "submit"
KERNEL_ID = "navin03/gemma4-swe-agent-submit"
TEXT_EXT = {".yaml", ".yml", ".md", ".txt", ".py", ".json"}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--note", default="")
    a = ap.parse_args()

    files = {}
    for p in sorted(SUB.rglob("*")):
        if not p.is_file():
            continue
        if p.suffix not in TEXT_EXT:
            raise SystemExit(f"non-text file {p}; ship adapters via an attached dataset instead")
        files[p.relative_to(SUB).as_posix()] = p.read_text(encoding="utf-8")

    code = f'''# Auto-generated by scripts/make_submit_notebook.py — edit submission/ locally, not this cell.
# Version: {a.version}  {a.note}
import zipfile
from pathlib import Path

FILES = {json.dumps(files, indent=1, ensure_ascii=False)}

out = Path("/kaggle/working/submission.zip")
with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
    for name in sorted(FILES):
        info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_DEFLATED
        info.external_attr = 0o644 << 16
        z.writestr(info, FILES[name].encode("utf-8"))

with zipfile.ZipFile(out) as z:
    names = z.namelist()
assert "agent.yaml" in names and not any(n.endswith("/") for n in names), names
import hashlib
print(out, out.stat().st_size, "bytes", "sha256", hashlib.sha256(out.read_bytes()).hexdigest())
print("\\n".join(names))
'''
    nb = {
        "cells": [
            {"cell_type": "markdown", "metadata": {},
             "source": [f"# Gemma 4 SWE agent — submission {a.version}\n\n{a.note}\n"]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
             "source": code.splitlines(keepends=True)},
        ],
        "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                     "language_info": {"name": "python"}},
        "nbformat": 4, "nbformat_minor": 4,
    }
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "submit.ipynb").write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    meta = {
        "id": KERNEL_ID,
        "title": "gemma4-swe-agent-submit",
        "code_file": "submit.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": False,
        "enable_tpu": False,
        "enable_internet": False,
        "dataset_sources": [],
        "competition_sources": ["gemma-4-developer-agent"],
        "kernel_sources": [],
        "model_sources": [],
    }
    (OUT / "kernel-metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(f"wrote {OUT} with {len(files)} files: {', '.join(files)}")


if __name__ == "__main__":
    main()
